name       : soundconverter
version    : 2.1.6
release    : 1
source     :
    - https://launchpad.net/soundconverter/trunk/2.1.6/+download/soundconverter-2.1.6.tar.xz : 2ffb6718d8e43a67be4d99e5a9c7b5cd82fce15d30b4861608b7d1666884a690
license    : GPL-3.0
component  : multimedia.audio
summary    : A simple sound converter application for the GNOME environment.
description: |
    A simple sound converter application for the GNOME environment.
builddeps  :
    - pkgconfig(gnome-python-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygtk-2.0)
    - gst-python
rundeps    :
    - gnome-python
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gst-python
    - pyorbit
    - python-gtk2
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
