name       : soundconverter
version    : 3.0.0
release    : 6
source     :
    - https://launchpad.net/soundconverter/trunk/3.0.0/+download/soundconverter-3.0.0.tar.xz : ecb47732f279fc91f761601a56bada0ce8b8fe25e2e2935ca6b793e26f713df3
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A simple sound converter application for the GNOME environment.
description: |
    A simple sound converter application for the GNOME environment.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - python3-gobject-devel
rundeps    :
    - gconf
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - python3-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-fdkaac-for-AAC-conversions.patch
    %configure
build      : |
    %make
install    : |
    %make_install
