name       : soundconverter
version    : 3.0.2
release    : 8
source     :
    - https://github.com/kassoulet/soundconverter/archive/3.0.2.tar.gz : 90fa4e44d5525a8cd6cb8f813fcd0512353f2f94c7b4a30c7acd6e713026bfd8
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A simple sound converter application for the GNOME environment.
description: |
    A simple sound converter application for the GNOME environment.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - python-gobject-devel
rundeps    :
    - gconf
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-fdkaac-for-AAC-conversions.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
